### ISSUE TITLE
deprecate the datatype attribute on item entities in the oval-system-characteristics-schema and its component schemas

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#111]
Consider deprecating datatype on OVAL Items. Datatype here is not ever used
since OVAL is really loosely typed. The only datatype that matters is the
datatype specified on the OVAL Object or OVAL State.

**Comment by solind** [comment]
An interesting point, nevertheless, punting!

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #57](https://github.com/OVAL-Community/OVAL/issues/57) via [**ZenHub**](https://www.zenhub.com/)
