### ISSUE TITLE
Consider adding run-as-user concept

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#117]
As an output of the AI/OVAL Developer Days conversation (March 2011), it was
proposed that the OVAL System Characteristics file would benefit from some
construct that allowed the specification of the user that the scan was run as. 

Outstanding questions that would need to be answered:
1. Would this simply record the user at a file level, or at a more detailed
   level.  (There are cases where an Interpreter would raise privileges during the
   scan, and should that information also get recorded?)
2. Would use of AI be an appropriate implementation?  Or something simpler?

Reference: Minutes from the Developer days conversation, available on the OVAL
web site.

http://oval.mitre.org/community/docs/OVAL_Spring_2011_Developer_Days_Minutes.pdf

**Comment by solind** [comment]
Note, XCCDF captures this information in the cdf12:identity element.  Punting to 5.12.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #55](https://github.com/OVAL-Community/OVAL/issues/55) via [**ZenHub**](https://www.zenhub.com/)
