### ISSUE TITLE
simplify reuse of highly reusable language components for external schemas

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#118]
Consider breaking out language constructs like result, datatype, and operation 
enumerations along with id type definitions so that they can be easily reused
by other standards that leverage OVAL.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #54](https://github.com/OVAL-Community/OVAL/issues/54) via [**ZenHub**](https://www.zenhub.com/)
