### ISSUE TITLE
add support for the collection of the file system type on Mac OSX 

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#120]
The file system type can be collected using "diskutil info
device".  We should add an fs_type entity for this value.  We
should also consider whether or not other information that can be collected
using "diskutil info device" needs to be collected.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #52](https://github.com/OVAL-Community/OVAL/issues/52) via [**ZenHub**](https://www.zenhub.com/)
