### ISSUE TITLE
discuss error handling in variables

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#123]
We should discuss if functions and components, in variables, should really be
returning errors or if the errors should be handled at a higher level such as
at the entities that reference them through the var_ref attribute.

Please see the following link for more information.

http://making-security-measurable.1364806.n2.nabble.com/OVAL-5-x-documentation-inconsistency-tp5460954.html

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #51](https://github.com/OVAL-Community/OVAL/issues/51) via [**ZenHub**](https://www.zenhub.com/)
