### ISSUE TITLE
spsiteurl and sitecollectionurl entity names should be consistent

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#125]
I think the spsiteurl object entity and the sitecollectionurl object entity are
referring to the same thing; that is, a SPSite object represents a Site
Collection.

Overview of the Sharepoint object model:
http://msdn.microsoft.com/en-us/library/ms473633.aspx

These two entity names should be consistent.  Here are the usages for both:

spsiteurl
- splist_object
- spcrawlrule_object

sitecollectionurl:
- spsiteadministration_object
- spsite_object
- bestbet_object
- infopolicycoll_object
- spgroup_object
- spweb_object

This issue if further confused by the fact that the API object name is not
exactly the same as the object model name.  In general, we should be consistent
in the schema whether we want to use the API object names (prefixed by SP, like
"SPSite", "SPWebApplication") or the object model names
("Site Collection", "Web Application").

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #50](https://github.com/OVAL-Community/OVAL/issues/50) via [**ZenHub**](https://www.zenhub.com/)
