### ISSUE TITLE
spdiagnosticslevel_object is underspecified

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#126]
The spdiagnosticslevel_object needs an additional 'diagnosticslevelname' entity
to specify the name of the IDiagnosticsLevel item to get.  The SPFarm has a
SPDiagnosticsService, which has many IDiagnosticsLevel objects, accessible by
name.

Some implementation details:
Related to tracker item #127, only the local SPDiagnosticsService is
accessible via SPDiagnosticsService.Local, and the farmname entity may not be
needed.  

http://msdn.microsoft.com/en-us/library/microsoft.sharepoint.administration.spdiagnosticsservice.local.aspx

An additional note is that even if it is possible to get other farms, the
SPDiagnosticsService does not seem to be accessible directly to the SPFarm:

http://msdn.microsoft.com/en-us/library/microsoft.sharepoint.administration.spfarm_members.aspx

The SPDiagnosticsService.GetItem method:

http://msdn.microsoft.com/en-us/library/ms437477%28v=office.12%29.aspx

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #49](https://github.com/OVAL-Community/OVAL/issues/49) via [**ZenHub**](https://www.zenhub.com/)
