### ISSUE TITLE
deprecate spfarm object entity - restrict to SPFarm.Local

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#127]
In several objects in the sharepoint schema, there is a farmname entity that
specifies an SPFarm name.  However, it is not possible to get a SPFarm with
only the farm name.  Accessing a SPFarm outside the local scope requires a
detailed connection string, with the SPFarm.Open method.  If the user does not
have permissions to access the farm, an exception will be thrown:

API: http://msdn.microsoft.com/en-us/library/ms453293.aspx
Example:
http://social.msdn.microsoft.com/Forums/en/sharepointdevelopment/thread/e54c5fb2-fd0d-4843-844b-b68ff568c614
"Should be something like: SPFarm farm = SPFarm.Open("Data
Source=server.domain.com;Initial Catalog=SharePoint_Config;Integrated
Security=SSPI");"

I think accessing a non-local SPFarm (that is, a farm that does not own the
current server, or a farm other than SPFarm.Local) may be out of scope for the
sharepoint schema.  This depends on the way Sharepoint administration is done,
and checking remote machines may not be in scope for the OVAL Interpreter: Is
it common for a single user to administrate several Sharepoint Farms?

In the case that the Sharepoint schema applies only to the local farm, the
following changes need to be made: the tests need to be rewritten to only apply
to the local farm, the farmname (or spfarmname) entity should be removed from
the object, and the schema noted that these tests will always gather
information from the local farm.  The farmname entity may potentially remain on
the state and item, if it is necessary to confirm the farm name.

This issue affects:
spantivirussettings_object
spdiagnosticsservice_object
spdiagnosticslevel_object
sppolicyfeature_object

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #48](https://github.com/OVAL-Community/OVAL/issues/48) via [**ZenHub**](https://www.zenhub.com/)
