### ISSUE TITLE
spweb_object may need additional entity

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#129]
I think that the spweb_object could use an additional entity, webapplicationurl,
to specify the SPWebApplication.  Currently the probe must iterate through all
the SPWebApplications and match the Site and Web.  The SPWebApplication should
probably be specified in the object (as well as the state and item).

Hierarchy:
SPWebApplication
-SPSite
--SPWeb

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #46](https://github.com/OVAL-Community/OVAL/issues/46) via [**ZenHub**](https://www.zenhub.com/)
