### ISSUE TITLE
spgroup_object is underspecified and needs additional entities

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#130]
spgroup_object does not properly specify a SPGroup object.  A Sharepoint Web
Site (SPWeb) belongs to many Groups, and there are many SPWebs in a SPSite. 
The current sitecollectionurl is insufficient to uniquely identify a SPGroup.

I propose the following changes:
1. Add a websiteurl entity to specify the SPWeb
2. Add a groupname entity to specify the SPGroup
3. Rename the "gname" state/item entity to "groupname"

This test is similar to the spweb_test, so they should be developed together.

Relevant API pages:
http://msdn.microsoft.com/en-us/library/microsoft.sharepoint.spgroup.aspx
http://msdn.microsoft.com/en-us/library/microsoft.sharepoint.spweb.aspx

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #45](https://github.com/OVAL-Community/OVAL/issues/45) via [**ZenHub**](https://www.zenhub.com/)
