### ISSUE TITLE
spweb_state unable to find secondarysitecolladmin entity in API

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#131]
I am not sure what the secondarysitecolladmin and entity in the spweb_state is
referring to.  The SPWeb does not have any members that seem to refer to such a
thing.

http://msdn.microsoft.com/en-us/library/microsoft.sharepoint.spweb_members.aspx

There is a SiteAdministrators property on the SPWeb, but no notion of priority
in that collection.  It is important to note that a SPSite (Site Collection)
contains many SPWebs (Web Sites).  It is the unfortunate nature of the API, but
is not clear which the schema is referring to.

The secondarysitecolladmin and secondsitecolladminenabled entities should be
examined, and perhaps removed.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #44](https://github.com/OVAL-Community/OVAL/issues/44) via [**ZenHub**](https://www.zenhub.com/)
