### ISSUE TITLE
fix UML diagrams in the specification to use the data model notation instead of the namespace notation

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#172]
Many UML diagrams in the specifications (language, windows, unix, etc.) use the namespace notation (e.g. oval-def::TestType) rather than the data model notation (e.g. OVAL Definitions::TestType).  We should update these UML diagrams to use the data model notation.

A few examples of this are the function constructs (e.g. CountFunctionType in oval-language-specification and file_test in the oval-windows-extension-specification), however, we should do our best to fix all instances of this.

**Comment by solind** [comment]
See https://github.com/OVALProject/Language/pull/198

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #41](https://github.com/OVAL-Community/OVAL/issues/41) via [**ZenHub**](https://www.zenhub.com/)
