### ISSUE TITLE
update Windows documentation to recommend case-insensitive operations be used where the values are case-insensitive

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#174]
Many constructs on Windows are case-insensitive.  We have some documentation around trustee_names, etc. stating this and recommend that content authors use case-insensitive operations.  We should make sure that we update other documentation where this is applicable.

Please see the following links for additional information.

http://making-security-measurable.1364806.n2.nabble.com/Case-Sensitivity-for-File-test-on-Windows-td7578876.html#a7578933

http://oval.mitre.org/language/version5.8/index.html#26239

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #40](https://github.com/OVAL-Community/OVAL/issues/40) via [**ZenHub**](https://www.zenhub.com/)
