### ISSUE TITLE
Does the oval-var:VariableType construct need to support signatures?

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#239]
The oval-def:DefinitionType, oval-def:TestType, oval-def:ObjectType, oval-def:StateType, and oval-def:VariableType constructs support signatures.  Does the oval-var:VariableType construct also need to support signatures?

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #36](https://github.com/OVAL-Community/OVAL/issues/36) via [**ZenHub**](https://www.zenhub.com/)
