### ISSUE TITLE
copyright statement in OVAL	artifacts

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#289]
I was just looking at an OVAL schema file and noticed it says: 
 
“© 2016, Center for Internet Security. All Rights Reserved.”
 
Looking at the OVAL Terms of Use (https://oval.cisecurity.org/terms), I believe it should say:
 
“© 2010, United States Government. All Rights Reserved.”

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #35](https://github.com/OVAL-Community/OVAL/issues/35) via [**ZenHub**](https://www.zenhub.com/)
