### ISSUE TITLE
Possible issue with the schematron rule for schema_version element.

### ISSUE THREAD

**Issue by dragosprisaca** [OVAL-Community/Language#293]
Hello,
 
The oval-common-schema.xsd (5.11.2) includes the following schematron rule:
“<sch:assert test="starts-with(.,$core_version_portion)"> This platform's version (<sch:value-of select="."/>) MUST match the core version being used: <sch:value-ofselect="$core_version_portion"/>.</sch:assert>”
 
This rule tests if the schema core version is the same as the one used in the platform’s version. The latest core version is 5.11.2 and the version of Windows schema is 5.11.1:1.3. The following excerpt will fail the schematron rule because the core schema version (5.11.2) does not match the core portion from the Windows extension platform (5.1.1.1:1.3):
    <generator>
        <oval:product_name>NIST Validation Content Generation Script</oval:product_name>
        <oval:product_version>1.0</oval:product_version>
        <oval:schema_version>5.11.2</oval:schema_version>
        <oval:schema_version platform="Windows">5.11.1:1.3</oval:schema_version>
        <oval:timestamp>2017-01-22T14:03:55-04:00</oval:timestamp>
    </generator>
 
Is the schematron rule incorrect or the content listed above? Please note that the core portion of all the extension schemas is 5.11.1.
 
Respectfully,
_Dragos.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #33](https://github.com/OVAL-Community/OVAL/issues/33) via [**ZenHub**](https://www.zenhub.com/)
