### ISSUE TITLE
OVAL directives do not provide an option to include or not System Characteristics data

### ISSUE THREAD

**Issue by dragosprisaca** [OVAL-Community/Language#294]
Hello,

The section 4.6 “OVAL Results” of the SCAP specification SP800-126r2 requires to produce OVAL results components expressed as “Single Machine Without System Characteristics” and “Single Machine With System Characteristics”. The OVAL directives for both requirements are the same:
<oval-res:directives include_source_definitions="false">
<oval-res:definition_true content="full" reported="true"/>
<oval-res:definition_false content="full" reported="true"/>
<oval-res:definition_unknown content="full" reported="true"/>
<oval-res:definition_error content="full" reported="true"/>
<oval-res:definition_not_evaluated content="full" reported="true"/>
<oval-res:definition_not_applicable content="full" reported="true"/>
</oval-res:directives>
The only difference between these results is the System Characteristics data which is included or not in the results.

The OVAL directives should provide an option to indicate whether the System Characteristics should or should not be included in the results. 

Respectfully,
_Dragos.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #32](https://github.com/OVAL-Community/OVAL/issues/32) via [**ZenHub**](https://www.zenhub.com/)
