### ISSUE TITLE
Fix EntityItemFileTypeType to fix backwards compatibility issue in Windows file_item caused by 5.11.2 update

### ISSUE THREAD

**Issue by vanderpol** [OVAL-Community/Language#295]
The Windows file test results from 5.11.1 no longer validate in 5.11.2, due to the removal of the FILE_ATTRIBUTE_DIRECTORY from the EntityItemFileTypeType.  

Here's the error we are seeing when validating against 5.11.2:

File " OVAL-Results_win-def_file_test.xml" did not load at line 287, pos 76, reason: 'FILE_ATTRIBUTE_DIRECTORY' violates enumeration constraint of 'FILE_TYPE_CHAR FILE_TYPE_DISK FILE_TYPE_PIPE FILE_TYPE_REMOTE FILE_TYPE_UNKNOWN '.
The element '{http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows}type' with value 'FILE_ATTRIBUTE_DIRECTORY' failed to parse.
, text: ' <win-sc:type>FILE_ATTRIBUTE_DIRECTORY</win-sc:type>'

The item in question is below:

                              <win-sc:file_item status="exists" id="1">
                                    <win-sc:filepath>C:\Program Files\Internet Explorer</win-sc:filepath>
                                    <win-sc:path>C:\Program Files\Internet Explorer</win-sc:path>
                                    <win-sc:filename></win-sc:filename>
                                    <win-sc:owner>NT SERVICE\TrustedInstaller</win-sc:owner>
                                    <win-sc:size datatype="int">0</win-sc:size>
                                    <win-sc:a_time datatype="int">131342918770000000</win-sc:a_time>
                                    <win-sc:c_time datatype="int">131131313970000000</win-sc:c_time>
                                    <win-sc:m_time datatype="int">131342918770000000</win-sc:m_time>
                                    <win-sc:ms_checksum></win-sc:ms_checksum>
                                    <win-sc:version datatype="version"></win-sc:version>
                                    <win-sc:type>FILE_ATTRIBUTE_DIRECTORY</win-sc:type>
                                    <win-sc:development_class></win-sc:development_class>
                                    <win-sc:company></win-sc:company>
                                    <win-sc:internal_name></win-sc:internal_name>
                                    <win-sc:language></win-sc:language>
                                    <win-sc:original_filename></win-sc:original_filename>
                                    <win-sc:product_name></win-sc:product_name>
                                    <win-sc:product_version datatype="version"></win-sc:product_version>
                                    <win-sc:windows_view>32_bit</win-sc:windows_view>
                              </win-sc:file_item>

https://github.com/OVALProject/Language/issues/275

Windows system characteristics from OVAL 5.11.1:

     <xsd:element name="file_item" substitutionGroup="oval-sc:item"> <TRUNCATED>
                              <xsd:element name="type" type="win-sc:EntityItemFileTypeType" minOccurs="0" maxOccurs="1">
                                   <xsd:annotation>
                                        <xsd:documentation>The type child element marks wether the file item describes a directory, named pipe, standard file, etc. These types are the return values for GetFileType, with the exception of FILE_ATTRIBUTE_DIRECTORY which is obtained by looking at GetFileAttributesEx.</xsd:documentation>
                                   </xsd:annotation>
                              </xsd:element>

    <xsd:complexType name="EntityItemFileTypeType">
          <xsd:annotation>
               <xsd:documentation>The EntityItemFileTypeType restricts a string value to a specific set of values that describe the different types of files. The empty string is also allowed to support empty elements associated with error conditions.</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleContent>
               <xsd:restriction base="oval-sc:EntityItemStringType">
                    <xsd:enumeration value="FILE_ATTRIBUTE_DIRECTORY">
                         <xsd:annotation>
                              <xsd:documentation>The handle identifies a directory.</xsd:documentation>
                         </xsd:annotation>
                    </xsd:enumeration>
                    <xsd:enumeration value="FILE_TYPE_CHAR">
                         <xsd:annotation>
                              <xsd:documentation>The specified file is a character file, typically an LPT device or a console.</xsd:documentation>
                         </xsd:annotation>
                    </xsd:enumeration>
<TRUNCATED>

Windows system characteristics from  5.11.2:

     <xsd:element name="file_item" substitutionGroup="oval-sc:item"> <TRUNCATED>
                              <xsd:element name="type" type="win-sc:EntityItemFileTypeType" minOccurs="0" maxOccurs="1">
                                   <xsd:annotation>
                                        <xsd:documentation>The type child element marks whether the file item describes a named pipe, standard file, etc. These types are the return values for GetFileType. For directories, this element must have a status of 'does not exist'.</xsd:documentation>
                                   </xsd:annotation>
                              </xsd:element>

     <xsd:complexType name="EntityItemFileTypeType">
          <xsd:annotation>
               <xsd:documentation>The EntityItemFileTypeType restricts a string value to a specific set of values that describe the different types of files. The empty string is also allowed to support empty elements associated with error conditions.</xsd:documentation>
          </xsd:annotation>
          <xsd:simpleContent>
               <xsd:restriction base="oval-sc:EntityItemStringType">
                    <xsd:enumeration value="FILE_TYPE_CHAR">
                         <xsd:annotation>
                              <xsd:documentation>The specified file is a character file, typically an LPT device or a console.</xsd:documentation>
                         </xsd:annotation>
                    </xsd:enumeration>

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #31](https://github.com/OVAL-Community/OVAL/issues/31) via [**ZenHub**](https://www.zenhub.com/)
