### ISSUE TITLE
The ldap_object and activedirectory_object do not support oval-def:filter

### ISSUE THREAD

**Issue by dragosprisaca** [OVAL-Community/Language#297]
The following objects: ind-def:ldap_object and win-def:activedirectory_object do not support oval-def:filter.

Respectfully,
_Dragos.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #29](https://github.com/OVAL-Community/OVAL/issues/29) via [**ZenHub**](https://www.zenhub.com/)
