### ISSUE TITLE
Solaris packageavoidlist_item entity mismatch with sample content

### ISSUE THREAD

**Issue by solind** [OVAL-Community/Language#299]
The sample content for the Solaris 5.11 packageavoidlist_item has a name entity:

https://github.com/OVALProject/Sandbox/blob/master/resources/x-solaris-updates/content/packageavoidlist_test/results.xml

However, the schema definition for the packageavoidlist_item has an FMRI entity.

Since the package avoid list seems to be name-based, and not fmri-based, perhaps the packageavoidlist_item fmri entity should be deprecated and replaced with a new name entity.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #26](https://github.com/OVAL-Community/OVAL/issues/26) via [**ZenHub**](https://www.zenhub.com/)

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #27](https://github.com/OVAL-Community/OVAL/issues/27) via [**ZenHub**](https://www.zenhub.com/)
