### ISSUE TITLE
Add kerberos-{test, object, state}

### ISSUE THREAD

**Issue by redhatrises** [OVAL-Community/Language#306]
There are ldap tests, objects, and states, but no kerberos tests, objects, and states. Being able to check kerberos settings would be beneficial for implementations that use the modern ldap/kerberos integration(s) especially if password length and other settings are held in kerberos and not in ldap.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #21](https://github.com/OVAL-Community/OVAL/issues/21) via [**ZenHub**](https://www.zenhub.com/)
