### ISSUE TITLE
port_version datatype needed for FreeBSD version comparisons

### ISSUE THREAD

**Issue by solind** [OVAL-Community/Language#307]
Sergey from Altex-Soft has brought to my attention the fact that FreeBSD packages (which can be checked in OVAL using the freebsd:port_test) have their own versioning logic — similar to how RedHat and Ubuntu/Debian package versions also have their own comparison logic.  Here is a page describing (to an extent, anyway) the FreeBSD version comparison logic:

https://vuxml.freebsd.org/freebsd/a63b15f9-97ff-11dc-9e48-0016179b2dd5.html

RedHat and Debian package versions are represented in OVAL using the evr_string and debian_evr_string datatypes in OVAL, but we currently have no way of representing port version strings.

**Comment by rag-altx** [comment]
Link about FreeBSD ports version comparison logic https://www.freebsd.org/doc/en/books/porters-handbook/makefile-naming.html

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #20](https://github.com/OVAL-Community/OVAL/issues/20) via [**ZenHub**](https://www.zenhub.com/)
