### ISSUE TITLE
Remove enumerations from MacOS SystemProfiler data_type element in object, state, and item

### ISSUE THREAD

**Issue by julmerII** [OVAL-Community/Language#308]
The MacOS SystemProfiler object, state, and item _data_type_ elements, we're running into a tangle.  OVAL specifies a valid values list (enumeration) for each (_EntityObjectDataTypeType, EntityStateDataTypeType_,  and _EntityItemDataTypeType_).  This list is incomplete when compared to the data_types available on the OS.  As has already happened, we should probably expect Apple to add more data_types to the SystemProfiler, over time.  For content authors who wish to use data_types not supported by OVAL, this causes constant XML validation error noise.  

'Seems there are two options.  Continually update the valid values lists for the _data_type_ elements as Apple changes them.  --OR-- Change those three elements to simple strings.

I don't see any real benefit in controlling these values.  The SCAP processor can retrieve the list of valid _data_types_ from the system being scanned and control the querying of info from the system according to those system-supplied data_type values.

I suggest we change the _data_type_ entities to be oval-def:EntityObjectStringType and oval-sc:EntityItemStringType.

Also, per Mr. Solin's suggestion we would need to modify the documentation to direct SCAP processors to use only those data_types actually found on the machine (via system_profiler --listDataTypes).

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #19](https://github.com/OVAL-Community/OVAL/issues/19) via [**ZenHub**](https://www.zenhub.com/)
