### ISSUE TITLE
Partial Unionsets(one side evals to error) should allow to deal with partial Data

### ISSUE THREAD

**Issue by Memnarch** [OVAL-Community/Language#309]
This issue is specific to Union-Sets, only.

**Problem**
When a Union-Set has one side that evals to "error", the whole set evals to error and therefore will bubble up as such and (mostly) stop evaluation of a test or even a whole definition. That happens easily when one object of the Set refers to a variable which has a failing var_check. But in a lot of cases, the partial data might already be enough(because checks above would only require atleast one item of the set to eval to true). Therefore it is currently quite unsafe to use a union-set to get a union of different items from different locations (i.e. files from different folders) to see if at least one of them meets a specific state or feed it to other mechanics.

**Proposal/rough Idea**
When an object of a Union-Set evals to error (and the other one (in)completes), the set could eval to (in)complete but add a "null_item" to the result in addition to the items delivered by the other object that evaluated to (in)complete. The "null_item" then simply has only the flag set to "error" and no other property/value. That would allow checks above the set(i.e. in tests/states or var_checks) to take into account that something isn't 100% right and only partial, without any changes to the definition as they are now. As long as a check requires for example only one item to eval to true, the collection with the null_item is sufficient. When a check would require all, that collection would fail and cause the same result as if the set had evaluated to error.

By introducing this "null_item", partial Union-Sets would work in situations where only partial data is needed anyway and behave as before when 100% of the returned items is expected to be true but isn't.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #18](https://github.com/OVAL-Community/OVAL/issues/18) via [**ZenHub**](https://www.zenhub.com/)
