### ISSUE TITLE
A field_operator is needed in EntityStateRecordType

### ISSUE THREAD

**Issue by solind** [OVAL-Community/Language#311]
In order to specify how to handle matching against multiple fields.  This would be analogous in operation to the operator attribute in StateType.

**Comment by solind** [comment]
Note: currently the documentation for EntityStateRecordType says:

```
During analysis of a system characteristics item, each field is analyzed and then the overall result for elements of this type is computed by logically anding the results for each field and then applying the entity_check attribute.
```

But, this is impossible.  If a field has an entity_check, it has to be evaluated with respect to matching item record fields BEFORE those results can be ANDed together.  So, fixing this should be addressed as part of this same issue.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #16](https://github.com/OVAL-Community/OVAL/issues/16) via [**ZenHub**](https://www.zenhub.com/)
