### ISSUE TITLE
esx-def:ViSdkManagedEntityBehaviors has invalid value ClusterComputerResource

### ISSUE THREAD

**Issue by solind** [OVAL-Community/Language#312]
Should be "ClusterComputeResource".  Let's deprecate the misspelling and add the correct enum value.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #15](https://github.com/OVAL-Community/OVAL/issues/15) via [**ZenHub**](https://www.zenhub.com/)
