### ISSUE TITLE
clarify the unix-def:password_test and the unix-def:shadow_test documentation

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#49]
There have been a few threads bringing up concerns with the existing unix-def:password_test and unix-def:shadow_test.  To address this, it may just require documentation updates or it could require the development of new tests (e.g. a test for checking user accounts on UNIX systems).  In doing so, we should make sure that we do not break any existing content that may already use the unix-def:password_test and unix-def:shadow_test.

Please see the following oval-developer-list posts for additional information.

http://making-security-measurable.1364806.n2.nabble.com/unix-password-and-unix-shadow-on-MacOS-X-tp7578477.html

http://making-security-measurable.1364806.n2.nabble.com/unix-password-test-tp7579458.html

http://making-security-measurable.1364806.n2.nabble.com/Does-ovaldi-implement-ObjectType-entity-var-check-tp7578413p7578426.html  (search for "Potential issues with OVAL regarding UNIX and external authentication sources")

**Comment by solind** [comment]
Punting to 5.12.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #67](https://github.com/OVAL-Community/OVAL/issues/67) via [**ZenHub**](https://www.zenhub.com/)
