### ISSUE TITLE
rename the win-def:accesstoken_state setrustedcredmanaccessnameright entity

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#50]
We need to rename the win-def:accesstoken_state setrustedcredmanaccessnameright entity to setrustedcredmanaccessprivilege to align with the privilege defined in the following Microsoft documentation.

http://msdn.microsoft.com/en-us/library/windows/desktop/bb530716(v=vs.85).aspx

Please see the following oval-developer-list post for more information.

http://making-security-measurable.1364806.n2.nabble.com/Access-Token-State-Element-Potential-Mismatch-tp7580102.html

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #66](https://github.com/OVAL-Community/OVAL/issues/66) via [**ZenHub**](https://www.zenhub.com/)
