### ISSUE TITLE
what interfaces should be included in oval-sc:system_info/interfaces?

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#52]
The current documentation states that oval-sc:system_info/interfaces should contain the network interfaces on a system which can be used to identify the system on a network.  However, it is unclear what interfaces should be included here.  For example, some systems might have network interfaces associated with virtual machines, should these be included, etc.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #65](https://github.com/OVAL-Community/OVAL/issues/65) via [**ZenHub**](https://www.zenhub.com/)
