### ISSUE TITLE
Investigate formatted datatype pattern restriction enforcement through schema

### ISSUE THREAD

**Issue by drothenberg** [OVAL-Community/Language#56]
Presently several datatypes such as version, IPv4, and evr_string represent structured information, yet are defined in the OVAL Schema as restricted to any string value. This would imply an IPv4 address of "one.two.three.four" is schema valid, despite its contradiction to the OVAL Specification.

There is an option to catch these errors earlier with the use of pattern matching for simpler formatted datatypes.

**Comment by solind** [comment]
Deferring to 5.12

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #64](https://github.com/OVAL-Community/OVAL/issues/64) via [**ZenHub**](https://www.zenhub.com/)
