### ISSUE TITLE
add the windows_view behavior to the win-def:peheader_test

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#59]
The win-def:peheader_test examines the pe headers executables, dlls, etc. which can be 32-bit or 64-bit. As a result, we should add support for the windows_view behavior in the win-def:peheader_test so we can support the collection of all files on a 64-bit Windows system.

**Comment by solind** [comment]
This attribute appears in win-def:FileBehaviors in the 5.11 release.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #63](https://github.com/OVAL-Community/OVAL/issues/63) via [**ZenHub**](https://www.zenhub.com/)
