### ISSUE TITLE
constant_variable needs to support record datatype

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#62]
In adding support for the new record datatype we neglected to update the
constant_variable to allow it to hold a record. The current
<constant_variable> structure allows a sequence of <value> elements
and looks like this:

```
<constant_variable id="oval:example:var:111" datatype="int" ...>
   <value>1</value>
   <value>2</value>
<constant_variable>
```

This structure needs to be updated to allow each value to be a record. Values
are currently limited to simple types(xsd:anySimpleType). In order for
variables to fully support the new record datatype the <value> element
needs to optionally allow named fields. This might look something like:

```
<constant_variable id="oval:example:var:111" datatype="record" ...>
    <record>
        <field name="name" datatype="string">user1</field>
        <field name="screensavertimeout" datatype="int">900</field>
    </record>
    <record>
        <field name="name" datatype="string">user2</field>
        <field name="screensavertimeout" datatype="int">600</field>
    </record>
</constant_variable>  
```

**Comment by solind** [comment]
Punting to 5.12.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #62](https://github.com/OVAL-Community/OVAL/issues/62) via [**ZenHub**](https://www.zenhub.com/)
