### ISSUE TITLE
consider moving the platform-specific datatypes from the core schemas to their corresponding component schemas

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#64]
We have a few datatypes that are platform-specific and are only used in the
corresponding component schemas.  We should consider moving them out of the
core schemas and into the appropriate component schemas.  Platform-specific
datatypes include:

evr_string (linux)
fileset_revision (hp-ux)
ios_version (cisco ios)

**Comment by solind** [comment]
Punting to 5.12.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #61](https://github.com/OVAL-Community/OVAL/issues/61) via [**ZenHub**](https://www.zenhub.com/)
