### ISSUE TITLE
can the macos value in the oval:FamilyEnumeration be deprecated in favor of just using the unix value?

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#71]
In the oval:FamilyEnumeration we have the following values.

-catos
-ios
-macos
-pixos
-undefined
-unix
-vmware_infrastructure
-windows

Under this enumeration, various unix-like platforms are covered under
"unix" including linux variants (RHEL, Debian, etc.), solaris, bsd
variants (FreeBSD, OpenBSD, etc.), and unix variants (HP-UX, IBM AIX, etc.). 
However, you could argue that MacOS is also a unix-like platform.  With that
said, would it make sense to deprecate the "macos" value and just use
the "unix" value instead? Or, is MacOS different enough from the other
unix-like platforms to justify having a separate "macos" value?

**Comment by solind** [comment]
There is too much MacOS content that relies on the family to deprecate it now.  (And arguably, there could be a cisco family instead of catos, ios, picos, etc.)

Let's punt on this until 6.0.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #60](https://github.com/OVAL-Community/OVAL/issues/60) via [**ZenHub**](https://www.zenhub.com/)
