### ISSUE TITLE
can we further specify the count function

### ISSUE THREAD

**Issue by djhaynes** [OVAL-Community/Language#88]
There was a question on the oval-developer-list that asked about whether or not
the count function should evaluate to 0 when it contains components that do not
exist or should it evaluate to error. Please see the following
oval-developer-list post for more information.

http://making-security-measurable.1364806.n2.nabble.com/count-function-against-component-evaluating-to-zero-values-tp7304434p7304434.html

Having the count function evaluate to 0 in this case makes sense, however, it
conflicts with current documentation of the object_component which states:

"The referenced OVAL Object specifies a set of OVAL Items to collect. Note

that an OVAL Object might identify 0, 1, or many OVAL Items on a system. If no

items are found on the system then an error should be reported when 
determining the value of an ObjectComponentType..."

Can we safely remove this documentation from the object_component? Can we
update the count function to evaluate to 0?

**Comment by solind** [comment]
AFAIK, pretty much everyone writing content understands that object_components whose objects don't exist generate errors.  So, I'll push this one out the 5.12 in case anyone wants to re-evaluate it then.

**Comment by zport** [comment]
Issue moved to [OVAL-Community/OVAL #59](https://github.com/OVAL-Community/OVAL/issues/59) via [**ZenHub**](https://www.zenhub.com/)
